from __future__ import annotations
from typing import Protocol, List, Optional
from src.domain.entities.cliente import Cliente, ClienteCreate, ClienteUpdate
from src.domain.entities.vehiculo import Vehiculo, VehiculoCreate, VehiculoUpdate
from src.domain.entities.orden import Orden, OrdenCreate, OrdenUpdate

class ClienteRepository(Protocol):
    def list(self) -> List[Cliente]: ...
    def get(self, id_cliente: int) -> Optional[Cliente]: ...
    def create(self, data: ClienteCreate) -> Cliente: ...
    def update(self, id_cliente: int, data: ClienteUpdate) -> Cliente: ...
    def delete(self, id_cliente: int) -> None: ...

class VehiculoRepository(Protocol):
    def list(self) -> List[Vehiculo]: ...
    def get(self, id_vehiculo: int) -> Optional[Vehiculo]: ...
    def create(self, data: VehiculoCreate) -> Vehiculo: ...
    def update(self, id_vehiculo: int, data: VehiculoUpdate) -> Vehiculo: ...
    def delete(self, id_vehiculo: int) -> None: ...

class OrdenRepository(Protocol):
    def list(self) -> List[Orden]: ...
    def get(self, id_orden: int) -> Optional[Orden]: ...
    def create(self, data: OrdenCreate) -> Orden: ...
    def update(self, id_orden: int, data: OrdenUpdate) -> Orden: ...
    def delete(self, id_orden: int) -> None: ...
